// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-tIlWPjRFXKCRYq150CPViBfKDQxcoPw',
    appId: '1:465131815765:web:857abcc6f0b885468ee5dc',
    messagingSenderId: '465131815765',
    projectId: 'online-ourse-application',
    authDomain: 'online-ourse-application.firebaseapp.com',
    storageBucket: 'online-ourse-application.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMNk1BP4a8mrA_np8GMkZCWRY7NKQyCU0',
    appId: '1:465131815765:android:1283d90fa31e70618ee5dc',
    messagingSenderId: '465131815765',
    projectId: 'online-ourse-application',
    storageBucket: 'online-ourse-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHBl8cg4dVLZiRSL5hswp8TsmuvJgl1Cw',
    appId: '1:465131815765:ios:a31184a2f15757828ee5dc',
    messagingSenderId: '465131815765',
    projectId: 'online-ourse-application',
    storageBucket: 'online-ourse-application.appspot.com',
    iosBundleId: 'com.example.onlineCourseApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHBl8cg4dVLZiRSL5hswp8TsmuvJgl1Cw',
    appId: '1:465131815765:ios:92c93bf11351000a8ee5dc',
    messagingSenderId: '465131815765',
    projectId: 'online-ourse-application',
    storageBucket: 'online-ourse-application.appspot.com',
    iosBundleId: 'com.example.onlineCourseApplication.RunnerTests',
  );
}
